version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directmeds-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-http://localhost:8080}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-directmeds}
      - DB_USERNAME=${DB_USERNAME:-directmeds}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    depends_on:
      - db
      - redis
    networks:
      - directmeds-network

  db:
    image: mysql:8.0
    container_name: directmeds-db
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_DATABASE:-directmeds}
      - MYSQL_USER=${DB_USERNAME:-directmeds}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - directmeds-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: directmeds-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - directmeds-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: directmeds-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME:-directmeds}
      - PMA_PASSWORD=${DB_PASSWORD:-secret}
    depends_on:
      - db
    networks:
      - directmeds-network
    profiles:
      - debug

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

networks:
  directmeds-network:
    driver: bridge