version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: directmeds-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./storage:/var/www/html/storage
      - ./public/uploads:/var/www/html/public/uploads
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=production
    depends_on:
      - mysql
      - redis
    networks:
      - directmeds-network
    labels:
      # Traefik labels for Coolify
      - "traefik.enable=true"
      - "traefik.http.routers.directmeds.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.directmeds.entrypoints=websecure"
      - "traefik.http.routers.directmeds.tls=true"
      - "traefik.http.routers.directmeds.tls.certresolver=letsencrypt"
      - "traefik.http.services.directmeds.loadbalancer.server.port=80"
      # Health check for Traefik
      - "traefik.http.services.directmeds.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.directmeds.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.directmeds.loadbalancer.healthcheck.timeout=10s"

  mysql:
    image: mysql:8.0
    container_name: directmeds-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - directmeds-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: directmeds-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - directmeds-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  directmeds-network:
    driver: bridge